### ISSUE TITLE
spin push spec doesn't work

### ISSUE THREAD

**Issue by abrisse** [jstorimer/spin#75]
When running the full test suite with rspec, I obtain an error:

```
$ spin push spec

Loading ["spec"]
/home/aymeric/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- /home/aymeric/dev/pm-platform/modules/wisdom/spec (LoadError)
    from /home/aymeric/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
    from /home/aymeric/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/aymeric/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /home/aymeric/.rvm/gems/ruby-1.9.3-p194/gems/spin-0.6.0/lib/spin.rb:278:in `block (2 levels) in fork_and_run'
```

I have the same error when I point out a line to test, like

```
$ spin push spec/lib/worker/manager_spec.rb:15

Loading ["spec/lib/worker/manager_spec.rb:15"]
/home/aymeric/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- /home/aymeric/dev/pm-platform/modules/wisdom/spec/lib/worker/manager_spec.rb:15 (LoadError)
    from /home/aymeric/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
```

By specifying a precise pattern, it works

```
$ spin push spec/models/*.rb
```

Any idea ?

**Comment by jstorimer** [comment]
I actually haven't used spin in a little while. I've been using [zeus](https://github.com/burke/zeus). But as far as I remember, this was never supported behaviour. spin was only meant to speed up an autotest-like workflow where you just run an individual test.

**Comment by abrisse** [comment]
Thanks for the feedback I will look at Zeus.

Concerning the supported behaviour, from https://github.com/jstorimer/spin:

```
Or, when using RSpec, run the whole suite:

spin push spec
```

and

```
Running a single RSpec example by adding a line number is also possible, e.g:

spin push spec/models/user_spec.rb:14
```

**Comment by jstorimer** [comment]
My bad! I'm not an rspec user, so I wasn't aware of that. Sorry for the confusion.
